export default {
    "version": "2.4.21",
    "type": "poster",
    "global": {
        "zoom": 1
    },
    "layouts": [{
            "title": "",
            "backgroundImage": null,
            "backgroundColor": "#FFFFFF",
            "backgroundRepeat": "no-repeat",
            "height": 480,
            "width": 640,
            "repeatId": null,
            "repeatGroup": null,
            "elements": [{
                    "transform": {
                        "a": 1,
                        "b": 0,
                        "c": 0,
                        "d": 1,
                        "tx": 0,
                        "ty": 0
                    },
                    "type": "image",
                    "category": "",
                    "opacity": 1,
                    "padding": [
                        0,
                        0,
                        0,
                        0
                    ],
                    "width": 263,
                    "height": 187.8571428571429,
                    "left": 57,
                    "top": 146.07142857142856,
                    "boxShadow": null,
                    "resize": 7,
                    "dragable": true,
                    "rotatable": true,
                    "editable": true,
                    "frozen": false,
                    "hidden": false,
                    "lock": false,
                    "style": {},
                    "borderRadius": 30,
                    "clip": null,
                    "url": "//st0.dancf.com/www/0/design/1465798469378-1.png",
                    "version": "2.4.21"
                },
                {
                    "transform": {
                        "a": 1,
                        "b": 0,
                        "c": 0,
                        "d": 1,
                        "tx": 0,
                        "ty": 0
                    },
                    "type": "text",
                    "category": "",
                    "opacity": 1,
                    "padding": [
                        0,
                        0,
                        0,
                        0
                    ],
                    "width": 99.99999999999997,
                    "height": 48.99999999999997,
                    "left": 422,
                    "top": 215.5,
                    "boxShadow": null,
                    "resize": 7,
                    "dragable": true,
                    "rotatable": true,
                    "editable": true,
                    "frozen": false,
                    "hidden": false,
                    "lock": false,
                    "style": {},
                    "borderRadius": 0,
                    "clip": null,
                    "color": "rgba(101, 16, 204, 1)",
                    "fontFamily": "Microsoft Yahei",
                    "fontStyle": "normal",
                    "fontWeight": 400,
                    "fontSize": 38,
                    "lineHeight": 1.2,
                    "letterSpacing": 0,
                    "textDecoration": "none",
                    "writingMode": "horizontal-tb",
                    "textAlign": "left",
                    "verticalAlign": "top",
                    "content": "OK",
                    "textShadow": null,
                    "version": "2.4.21"
                }
            ],
            "top": 0
        },
        {
            "title": "",
            "backgroundImage": null,
            "backgroundColor": "#FFFFFF",
            "backgroundRepeat": "no-repeat",
            "height": 480,
            "width": 640,
            "repeatId": null,
            "repeatGroup": null,
            "elements": [{
                    "transform": {
                        "a": 1,
                        "b": 0,
                        "c": 0,
                        "d": 1,
                        "tx": 0,
                        "ty": 0
                    },
                    "type": "text",
                    "category": "",
                    "opacity": 1,
                    "padding": [
                        0,
                        0,
                        0,
                        0
                    ],
                    "width": 120,
                    "height": 24,
                    "left": 237,
                    "top": 143,
                    "boxShadow": null,
                    "resize": 4,
                    "dragable": true,
                    "rotatable": true,
                    "editable": true,
                    "frozen": false,
                    "hidden": false,
                    "lock": false,
                    "style": {},
                    "borderRadius": 0,
                    "clip": null,
                    "color": "rgba(255,102,0,0.8)",
                    "fontFamily": "Microsoft Yahei",
                    "fontStyle": "normal",
                    "fontWeight": 400,
                    "fontSize": 20,
                    "lineHeight": 1.2,
                    "letterSpacing": 0,
                    "textDecoration": "none",
                    "writingMode": "horizontal-tb",
                    "textAlign": "left",
                    "verticalAlign": "top",
                    "content": "请输入文字",
                    "textShadow": null,
                    "version": "2.4.21"
                },
                {
                    "transform": {
                        "a": 1,
                        "b": 0,
                        "c": 0,
                        "d": 1,
                        "tx": 0,
                        "ty": 0
                    },
                    "type": "image",
                    "category": "",
                    "opacity": 1,
                    "padding": [
                        0,
                        0,
                        0,
                        0
                    ],
                    "width": 436,
                    "height": 226.42857142857144,
                    "left": 102,
                    "top": 205.78571428571428,
                    "boxShadow": null,
                    "resize": 7,
                    "dragable": true,
                    "rotatable": true,
                    "editable": true,
                    "frozen": false,
                    "hidden": false,
                    "lock": false,
                    "style": {},
                    "borderRadius": 30,
                    "clip": null,
                    "url": "//st0.dancf.com/www/0/design/1465798469378-1.png",
                    "version": "2.4.21"
                }
            ],
            "top": 480
        }
    ]
}